/*
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PactDSLUiModule extends AbstractPactDSLUiModule {

	public PactDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
