/*
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPactDSLScopeProvider extends DelegatingScopeProvider {
}
