/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>By Email</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.ByEmail#getEmailAddress <em>Email Address</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getByEmail()
 * @model
 * @generated
 */
public interface ByEmail extends FormalityType
{
  /**
   * Returns the value of the '<em><b>Email Address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Email Address</em>' attribute.
   * @see #setEmailAddress(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getByEmail_EmailAddress()
   * @model
   * @generated
   */
  String getEmailAddress();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.ByEmail#getEmailAddress <em>Email Address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Email Address</em>' attribute.
   * @see #getEmailAddress()
   * @generated
   */
  void setEmailAddress(String value);

} // ByEmail
