/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Company Number</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.CompanyNumber#getCompanyNumber <em>Company Number</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCompanyNumber()
 * @model
 * @generated
 */
public interface CompanyNumber extends FeatureType
{
  /**
   * Returns the value of the '<em><b>Company Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Company Number</em>' attribute.
   * @see #setCompanyNumber(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCompanyNumber_CompanyNumber()
   * @model
   * @generated
   */
  String getCompanyNumber();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.CompanyNumber#getCompanyNumber <em>Company Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Company Number</em>' attribute.
   * @see #getCompanyNumber()
   * @generated
   */
  void setCompanyNumber(String value);

} // CompanyNumber
