/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constraint Party</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.ConstraintParty#getForbiddenAction <em>Forbidden Action</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getConstraintParty()
 * @model
 * @generated
 */
public interface ConstraintParty extends PrimaryObligationType
{
  /**
   * Returns the value of the '<em><b>Forbidden Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forbidden Action</em>' attribute.
   * @see #setForbiddenAction(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getConstraintParty_ForbiddenAction()
   * @model
   * @generated
   */
  String getForbiddenAction();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.ConstraintParty#getForbiddenAction <em>Forbidden Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forbidden Action</em>' attribute.
   * @see #getForbiddenAction()
   * @generated
   */
  void setForbiddenAction(String value);

} // ConstraintParty
