/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.CustomAction#getCustomAction <em>Custom Action</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCustomAction()
 * @model
 * @generated
 */
public interface CustomAction extends ActionType
{
  /**
   * Returns the value of the '<em><b>Custom Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Action</em>' attribute.
   * @see #setCustomAction(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCustomAction_CustomAction()
   * @model
   * @generated
   */
  String getCustomAction();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.CustomAction#getCustomAction <em>Custom Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Action</em>' attribute.
   * @see #getCustomAction()
   * @generated
   */
  void setCustomAction(String value);

} // CustomAction
