/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.CustomFeature#getCustomFeature <em>Custom Feature</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCustomFeature()
 * @model
 * @generated
 */
public interface CustomFeature extends FeatureType
{
  /**
   * Returns the value of the '<em><b>Custom Feature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Feature</em>' attribute.
   * @see #setCustomFeature(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCustomFeature_CustomFeature()
   * @model
   * @generated
   */
  String getCustomFeature();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.CustomFeature#getCustomFeature <em>Custom Feature</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Feature</em>' attribute.
   * @see #getCustomFeature()
   * @generated
   */
  void setCustomFeature(String value);

} // CustomFeature
