/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Obligation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.CustomObligation#getCustomObligation <em>Custom Obligation</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCustomObligation()
 * @model
 * @generated
 */
public interface CustomObligation extends PrimaryObligationType
{
  /**
   * Returns the value of the '<em><b>Custom Obligation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Obligation</em>' attribute.
   * @see #setCustomObligation(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getCustomObligation_CustomObligation()
   * @model
   * @generated
   */
  String getCustomObligation();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.CustomObligation#getCustomObligation <em>Custom Obligation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Obligation</em>' attribute.
   * @see #getCustomObligation()
   * @generated
   */
  void setCustomObligation(String value);

} // CustomObligation
