/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getFeatureType()
 * @model
 * @generated
 */
public interface FeatureType extends EObject
{
} // FeatureType
