/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Feature#getFeaturetype <em>Featuretype</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Featuretype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Featuretype</em>' containment reference.
   * @see #setFeaturetype(FeatureType)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getFeature_Featuretype()
   * @model containment="true"
   * @generated
   */
  FeatureType getFeaturetype();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Feature#getFeaturetype <em>Featuretype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Featuretype</em>' containment reference.
   * @see #getFeaturetype()
   * @generated
   */
  void setFeaturetype(FeatureType value);

} // Feature
