/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>For Breach</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.ForBreach#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.ForBreach#getObligationBreached <em>Obligation Breached</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.ForBreach#getRemedialScheme <em>Remedial Scheme</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getForBreach()
 * @model
 * @generated
 */
public interface ForBreach extends TerminationType
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Party)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getForBreach_SuperType()
   * @model
   * @generated
   */
  Party getSuperType();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.ForBreach#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Party value);

  /**
   * Returns the value of the '<em><b>Obligation Breached</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obligation Breached</em>' attribute.
   * @see #setObligationBreached(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getForBreach_ObligationBreached()
   * @model
   * @generated
   */
  String getObligationBreached();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.ForBreach#getObligationBreached <em>Obligation Breached</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obligation Breached</em>' attribute.
   * @see #getObligationBreached()
   * @generated
   */
  void setObligationBreached(String value);

  /**
   * Returns the value of the '<em><b>Remedial Scheme</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Remedial Scheme</em>' attribute.
   * @see #setRemedialScheme(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getForBreach_RemedialScheme()
   * @model
   * @generated
   */
  String getRemedialScheme();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.ForBreach#getRemedialScheme <em>Remedial Scheme</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Remedial Scheme</em>' attribute.
   * @see #getRemedialScheme()
   * @generated
   */
  void setRemedialScheme(String value);

} // ForBreach
