/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Given Written Consent</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getGivenWrittenConsent()
 * @model
 * @generated
 */
public interface GivenWrittenConsent extends ActionType
{
} // GivenWrittenConsent
