/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>In Writing</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.InWriting#getCustomWritingFormality <em>Custom Writing Formality</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getInWriting()
 * @model
 * @generated
 */
public interface InWriting extends FormalityType
{
  /**
   * Returns the value of the '<em><b>Custom Writing Formality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Writing Formality</em>' attribute.
   * @see #setCustomWritingFormality(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getInWriting_CustomWritingFormality()
   * @model
   * @generated
   */
  String getCustomWritingFormality();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.InWriting#getCustomWritingFormality <em>Custom Writing Formality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Writing Formality</em>' attribute.
   * @see #getCustomWritingFormality()
   * @generated
   */
  void setCustomWritingFormality(String value);

} // InWriting
