/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Liability To Party</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getLiabilityToParty()
 * @model
 * @generated
 */
public interface LiabilityToParty extends LiabilityType
{
} // LiabilityToParty
