/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Liability Third Party</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getLiabilityThirdParty()
 * @model
 * @generated
 */
public interface LiabilityThirdParty extends LiabilityType
{
} // LiabilityThirdParty
