/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getTitle <em>Title</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getDay <em>Day</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getMonth <em>Month</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getYear <em>Year</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getEntityTypes <em>Entity Types</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getFormalityTypes <em>Formality Types</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getActionTypes <em>Action Types</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getStateTypes <em>State Types</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getPrimaryObligationTypes <em>Primary Obligation Types</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getTerminationTypes <em>Termination Types</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getBoilerplateTypes <em>Boilerplate Types</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see #setDay(int)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_Day()
   * @model
   * @generated
   */
  int getDay();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see #getDay()
   * @generated
   */
  void setDay(int value);

  /**
   * Returns the value of the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Month</em>' attribute.
   * @see #setMonth(int)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_Month()
   * @model
   * @generated
   */
  int getMonth();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getMonth <em>Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Month</em>' attribute.
   * @see #getMonth()
   * @generated
   */
  void setMonth(int value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Model#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

  /**
   * Returns the value of the '<em><b>Entity Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.EntityType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entity Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_EntityTypes()
   * @model containment="true"
   * @generated
   */
  EList<EntityType> getEntityTypes();

  /**
   * Returns the value of the '<em><b>Formality Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.FormalityType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Formality Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_FormalityTypes()
   * @model containment="true"
   * @generated
   */
  EList<FormalityType> getFormalityTypes();

  /**
   * Returns the value of the '<em><b>Action Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.ActionType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_ActionTypes()
   * @model containment="true"
   * @generated
   */
  EList<ActionType> getActionTypes();

  /**
   * Returns the value of the '<em><b>State Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.StateType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_StateTypes()
   * @model containment="true"
   * @generated
   */
  EList<StateType> getStateTypes();

  /**
   * Returns the value of the '<em><b>Primary Obligation Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.PrimaryObligationType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Obligation Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_PrimaryObligationTypes()
   * @model containment="true"
   * @generated
   */
  EList<PrimaryObligationType> getPrimaryObligationTypes();

  /**
   * Returns the value of the '<em><b>Termination Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.TerminationType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termination Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_TerminationTypes()
   * @model containment="true"
   * @generated
   */
  EList<TerminationType> getTerminationTypes();

  /**
   * Returns the value of the '<em><b>Boilerplate Types</b></em>' containment reference list.
   * The list contents are of type {@link imperialmsc.lmw21.pactdsl.pactDSL.BoilerplateType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boilerplate Types</em>' containment reference list.
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getModel_BoilerplateTypes()
   * @model containment="true"
   * @generated
   */
  EList<BoilerplateType> getBoilerplateTypes();

} // Model
