/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Notices</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Notices#getCustomNotice <em>Custom Notice</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getNotices()
 * @model
 * @generated
 */
public interface Notices extends BoilerplateType
{
  /**
   * Returns the value of the '<em><b>Custom Notice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Notice</em>' attribute.
   * @see #setCustomNotice(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getNotices_CustomNotice()
   * @model
   * @generated
   */
  String getCustomNotice();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Notices#getCustomNotice <em>Custom Notice</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Notice</em>' attribute.
   * @see #getCustomNotice()
   * @generated
   */
  void setCustomNotice(String value);

} // Notices
