/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>On Insolvency Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.OnInsolvencyEvent#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.OnInsolvencyEvent#getInsolvencyEvent <em>Insolvency Event</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOnInsolvencyEvent()
 * @model
 * @generated
 */
public interface OnInsolvencyEvent extends TerminationType
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Party)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOnInsolvencyEvent_SuperType()
   * @model
   * @generated
   */
  Party getSuperType();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.OnInsolvencyEvent#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Party value);

  /**
   * Returns the value of the '<em><b>Insolvency Event</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Insolvency Event</em>' attribute.
   * @see #setInsolvencyEvent(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOnInsolvencyEvent_InsolvencyEvent()
   * @model
   * @generated
   */
  String getInsolvencyEvent();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.OnInsolvencyEvent#getInsolvencyEvent <em>Insolvency Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Insolvency Event</em>' attribute.
   * @see #getInsolvencyEvent()
   * @generated
   */
  void setInsolvencyEvent(String value);

} // OnInsolvencyEvent
