/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>On Reasonable Notice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.OnReasonableNotice#getSuperType <em>Super Type</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOnReasonableNotice()
 * @model
 * @generated
 */
public interface OnReasonableNotice extends TerminationType
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(EObject)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOnReasonableNotice_SuperType()
   * @model
   * @generated
   */
  EObject getSuperType();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.OnReasonableNotice#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(EObject value);

} // OnReasonableNotice
