/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ownership</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.Ownership#getCustomOwnership <em>Custom Ownership</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOwnership()
 * @model
 * @generated
 */
public interface Ownership extends StateType
{
  /**
   * Returns the value of the '<em><b>Custom Ownership</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Ownership</em>' attribute.
   * @see #setCustomOwnership(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getOwnership_CustomOwnership()
   * @model
   * @generated
   */
  String getCustomOwnership();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.Ownership#getCustomOwnership <em>Custom Ownership</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Ownership</em>' attribute.
   * @see #getCustomOwnership()
   * @generated
   */
  void setCustomOwnership(String value);

} // Ownership
