/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage
 * @generated
 */
public interface PactDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  PactDSLFactory eINSTANCE = imperialmsc.lmw21.pactdsl.pactDSL.impl.PactDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Entity Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entity Type</em>'.
   * @generated
   */
  EntityType createEntityType();

  /**
   * Returns a new object of class '<em>Effective Date</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Effective Date</em>'.
   * @generated
   */
  EffectiveDate createEffectiveDate();

  /**
   * Returns a new object of class '<em>Party</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Party</em>'.
   * @generated
   */
  Party createParty();

  /**
   * Returns a new object of class '<em>Third Party</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Third Party</em>'.
   * @generated
   */
  ThirdParty createThirdParty();

  /**
   * Returns a new object of class '<em>Subject Matter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Subject Matter</em>'.
   * @generated
   */
  SubjectMatter createSubjectMatter();

  /**
   * Returns a new object of class '<em>Defined Term</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Defined Term</em>'.
   * @generated
   */
  DefinedTerm createDefinedTerm();

  /**
   * Returns a new object of class '<em>Address</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Address</em>'.
   * @generated
   */
  Address createAddress();

  /**
   * Returns a new object of class '<em>Company Number</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Company Number</em>'.
   * @generated
   */
  CompanyNumber createCompanyNumber();

  /**
   * Returns a new object of class '<em>Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Feature</em>'.
   * @generated
   */
  Feature createFeature();

  /**
   * Returns a new object of class '<em>Formality Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Formality Type</em>'.
   * @generated
   */
  FormalityType createFormalityType();

  /**
   * Returns a new object of class '<em>In Writing</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>In Writing</em>'.
   * @generated
   */
  InWriting createInWriting();

  /**
   * Returns a new object of class '<em>By Email</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>By Email</em>'.
   * @generated
   */
  ByEmail createByEmail();

  /**
   * Returns a new object of class '<em>Giving Notice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Giving Notice</em>'.
   * @generated
   */
  GivingNotice createGivingNotice();

  /**
   * Returns a new object of class '<em>Custom Formality</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Custom Formality</em>'.
   * @generated
   */
  CustomFormality createCustomFormality();

  /**
   * Returns a new object of class '<em>Action Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action Type</em>'.
   * @generated
   */
  ActionType createActionType();

  /**
   * Returns a new object of class '<em>Given Consent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Given Consent</em>'.
   * @generated
   */
  GivenConsent createGivenConsent();

  /**
   * Returns a new object of class '<em>Given Written Consent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Given Written Consent</em>'.
   * @generated
   */
  GivenWrittenConsent createGivenWrittenConsent();

  /**
   * Returns a new object of class '<em>State Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State Type</em>'.
   * @generated
   */
  StateType createStateType();

  /**
   * Returns a new object of class '<em>Ownership</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ownership</em>'.
   * @generated
   */
  Ownership createOwnership();

  /**
   * Returns a new object of class '<em>Right To Use</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Right To Use</em>'.
   * @generated
   */
  RightToUse createRightToUse();

  /**
   * Returns a new object of class '<em>Primary Obligation Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Primary Obligation Type</em>'.
   * @generated
   */
  PrimaryObligationType createPrimaryObligationType();

  /**
   * Returns a new object of class '<em>Payment Obligation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Payment Obligation</em>'.
   * @generated
   */
  PaymentObligation createPaymentObligation();

  /**
   * Returns a new object of class '<em>Delivery Obligation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Delivery Obligation</em>'.
   * @generated
   */
  DeliveryObligation createDeliveryObligation();

  /**
   * Returns a new object of class '<em>Transfer Obligation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transfer Obligation</em>'.
   * @generated
   */
  TransferObligation createTransferObligation();

  /**
   * Returns a new object of class '<em>Licence Obligation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Licence Obligation</em>'.
   * @generated
   */
  LicenceObligation createLicenceObligation();

  /**
   * Returns a new object of class '<em>Constraint Party</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Party</em>'.
   * @generated
   */
  ConstraintParty createConstraintParty();

  /**
   * Returns a new object of class '<em>Constraint Third Party</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Constraint Third Party</em>'.
   * @generated
   */
  ConstraintThirdParty createConstraintThirdParty();

  /**
   * Returns a new object of class '<em>Termination Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Termination Type</em>'.
   * @generated
   */
  TerminationType createTerminationType();

  /**
   * Returns a new object of class '<em>For Convenience</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>For Convenience</em>'.
   * @generated
   */
  ForConvenience createForConvenience();

  /**
   * Returns a new object of class '<em>On Reasonable Notice</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>On Reasonable Notice</em>'.
   * @generated
   */
  OnReasonableNotice createOnReasonableNotice();

  /**
   * Returns a new object of class '<em>For Breach</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>For Breach</em>'.
   * @generated
   */
  ForBreach createForBreach();

  /**
   * Returns a new object of class '<em>On Insolvency Event</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>On Insolvency Event</em>'.
   * @generated
   */
  OnInsolvencyEvent createOnInsolvencyEvent();

  /**
   * Returns a new object of class '<em>Custom Termination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Custom Termination</em>'.
   * @generated
   */
  CustomTermination createCustomTermination();

  /**
   * Returns a new object of class '<em>Boilerplate Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boilerplate Type</em>'.
   * @generated
   */
  BoilerplateType createBoilerplateType();

  /**
   * Returns a new object of class '<em>Applicable Law</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Applicable Law</em>'.
   * @generated
   */
  ApplicableLaw createApplicableLaw();

  /**
   * Returns a new object of class '<em>Jurisdiction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Jurisdiction</em>'.
   * @generated
   */
  Jurisdiction createJurisdiction();

  /**
   * Returns a new object of class '<em>Notices</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Notices</em>'.
   * @generated
   */
  Notices createNotices();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  PactDSLPackage getPactDSLPackage();

} //PactDSLFactory
