/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right To Use</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.RightToUse#getCustomUsage <em>Custom Usage</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getRightToUse()
 * @model
 * @generated
 */
public interface RightToUse extends StateType
{
  /**
   * Returns the value of the '<em><b>Custom Usage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Usage</em>' attribute.
   * @see #setCustomUsage(String)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getRightToUse_CustomUsage()
   * @model
   * @generated
   */
  String getCustomUsage();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.RightToUse#getCustomUsage <em>Custom Usage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Usage</em>' attribute.
   * @see #getCustomUsage()
   * @generated
   */
  void setCustomUsage(String value);

} // RightToUse
