/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transfer Obligation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation#getDay <em>Day</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation#getMonth <em>Month</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation#getYear <em>Year</em>}</li>
 * </ul>
 *
 * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getTransferObligation()
 * @model
 * @generated
 */
public interface TransferObligation extends PrimaryObligationType
{
  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see #setDay(int)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getTransferObligation_Day()
   * @model
   * @generated
   */
  int getDay();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see #getDay()
   * @generated
   */
  void setDay(int value);

  /**
   * Returns the value of the '<em><b>Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Month</em>' attribute.
   * @see #setMonth(int)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getTransferObligation_Month()
   * @model
   * @generated
   */
  int getMonth();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation#getMonth <em>Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Month</em>' attribute.
   * @see #getMonth()
   * @generated
   */
  void setMonth(int value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#getTransferObligation_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

} // TransferObligation
