/*
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.ui.tests;

import com.google.inject.Injector;
import imperialmsc.lmw21.pactdsl.ui.internal.PactdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PactDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PactdslActivator.getInstance().getInjector("imperialmsc.lmw21.pactdsl.PactDSL");
	}

}
