/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.CustomBoilerplate;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Custom Boilerplate</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.CustomBoilerplateImpl#getCustomBoilerplate <em>Custom Boilerplate</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CustomBoilerplateImpl extends BoilerplateTypeImpl implements CustomBoilerplate
{
  /**
   * The default value of the '{@link #getCustomBoilerplate() <em>Custom Boilerplate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomBoilerplate()
   * @generated
   * @ordered
   */
  protected static final String CUSTOM_BOILERPLATE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCustomBoilerplate() <em>Custom Boilerplate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomBoilerplate()
   * @generated
   * @ordered
   */
  protected String customBoilerplate = CUSTOM_BOILERPLATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CustomBoilerplateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.CUSTOM_BOILERPLATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCustomBoilerplate()
  {
    return customBoilerplate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCustomBoilerplate(String newCustomBoilerplate)
  {
    String oldCustomBoilerplate = customBoilerplate;
    customBoilerplate = newCustomBoilerplate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.CUSTOM_BOILERPLATE__CUSTOM_BOILERPLATE, oldCustomBoilerplate, customBoilerplate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.CUSTOM_BOILERPLATE__CUSTOM_BOILERPLATE:
        return getCustomBoilerplate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.CUSTOM_BOILERPLATE__CUSTOM_BOILERPLATE:
        setCustomBoilerplate((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.CUSTOM_BOILERPLATE__CUSTOM_BOILERPLATE:
        setCustomBoilerplate(CUSTOM_BOILERPLATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.CUSTOM_BOILERPLATE__CUSTOM_BOILERPLATE:
        return CUSTOM_BOILERPLATE_EDEFAULT == null ? customBoilerplate != null : !CUSTOM_BOILERPLATE_EDEFAULT.equals(customBoilerplate);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (customBoilerplate: ");
    result.append(customBoilerplate);
    result.append(')');
    return result.toString();
  }

} //CustomBoilerplateImpl
