/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.InWriting;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>In Writing</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.InWritingImpl#getCustomWritingFormality <em>Custom Writing Formality</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InWritingImpl extends FormalityTypeImpl implements InWriting
{
  /**
   * The default value of the '{@link #getCustomWritingFormality() <em>Custom Writing Formality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomWritingFormality()
   * @generated
   * @ordered
   */
  protected static final String CUSTOM_WRITING_FORMALITY_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCustomWritingFormality() <em>Custom Writing Formality</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomWritingFormality()
   * @generated
   * @ordered
   */
  protected String customWritingFormality = CUSTOM_WRITING_FORMALITY_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InWritingImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.IN_WRITING;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCustomWritingFormality()
  {
    return customWritingFormality;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCustomWritingFormality(String newCustomWritingFormality)
  {
    String oldCustomWritingFormality = customWritingFormality;
    customWritingFormality = newCustomWritingFormality;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.IN_WRITING__CUSTOM_WRITING_FORMALITY, oldCustomWritingFormality, customWritingFormality));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.IN_WRITING__CUSTOM_WRITING_FORMALITY:
        return getCustomWritingFormality();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.IN_WRITING__CUSTOM_WRITING_FORMALITY:
        setCustomWritingFormality((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.IN_WRITING__CUSTOM_WRITING_FORMALITY:
        setCustomWritingFormality(CUSTOM_WRITING_FORMALITY_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.IN_WRITING__CUSTOM_WRITING_FORMALITY:
        return CUSTOM_WRITING_FORMALITY_EDEFAULT == null ? customWritingFormality != null : !CUSTOM_WRITING_FORMALITY_EDEFAULT.equals(customWritingFormality);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (customWritingFormality: ");
    result.append(customWritingFormality);
    result.append(')');
    return result.toString();
  }

} //InWritingImpl
