/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.DefinedTerm;
import imperialmsc.lmw21.pactdsl.pactDSL.Jurisdiction;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Jurisdiction</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.JurisdictionImpl#getCustomJurisdiction <em>Custom Jurisdiction</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.JurisdictionImpl#getDefinition <em>Definition</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JurisdictionImpl extends BoilerplateTypeImpl implements Jurisdiction
{
  /**
   * The default value of the '{@link #getCustomJurisdiction() <em>Custom Jurisdiction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomJurisdiction()
   * @generated
   * @ordered
   */
  protected static final String CUSTOM_JURISDICTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCustomJurisdiction() <em>Custom Jurisdiction</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomJurisdiction()
   * @generated
   * @ordered
   */
  protected String customJurisdiction = CUSTOM_JURISDICTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getDefinition() <em>Definition</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefinition()
   * @generated
   * @ordered
   */
  protected EList<DefinedTerm> definition;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JurisdictionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.JURISDICTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCustomJurisdiction()
  {
    return customJurisdiction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCustomJurisdiction(String newCustomJurisdiction)
  {
    String oldCustomJurisdiction = customJurisdiction;
    customJurisdiction = newCustomJurisdiction;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.JURISDICTION__CUSTOM_JURISDICTION, oldCustomJurisdiction, customJurisdiction));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<DefinedTerm> getDefinition()
  {
    if (definition == null)
    {
      definition = new EObjectContainmentEList<DefinedTerm>(DefinedTerm.class, this, PactDSLPackage.JURISDICTION__DEFINITION);
    }
    return definition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PactDSLPackage.JURISDICTION__DEFINITION:
        return ((InternalEList<?>)getDefinition()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.JURISDICTION__CUSTOM_JURISDICTION:
        return getCustomJurisdiction();
      case PactDSLPackage.JURISDICTION__DEFINITION:
        return getDefinition();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.JURISDICTION__CUSTOM_JURISDICTION:
        setCustomJurisdiction((String)newValue);
        return;
      case PactDSLPackage.JURISDICTION__DEFINITION:
        getDefinition().clear();
        getDefinition().addAll((Collection<? extends DefinedTerm>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.JURISDICTION__CUSTOM_JURISDICTION:
        setCustomJurisdiction(CUSTOM_JURISDICTION_EDEFAULT);
        return;
      case PactDSLPackage.JURISDICTION__DEFINITION:
        getDefinition().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.JURISDICTION__CUSTOM_JURISDICTION:
        return CUSTOM_JURISDICTION_EDEFAULT == null ? customJurisdiction != null : !CUSTOM_JURISDICTION_EDEFAULT.equals(customJurisdiction);
      case PactDSLPackage.JURISDICTION__DEFINITION:
        return definition != null && !definition.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (customJurisdiction: ");
    result.append(customJurisdiction);
    result.append(')');
    return result.toString();
  }

} //JurisdictionImpl
