/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.OnInsolvencyEvent;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;
import imperialmsc.lmw21.pactdsl.pactDSL.Party;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>On Insolvency Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.OnInsolvencyEventImpl#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.OnInsolvencyEventImpl#getInsolvencyEvent <em>Insolvency Event</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OnInsolvencyEventImpl extends TerminationTypeImpl implements OnInsolvencyEvent
{
  /**
   * The cached value of the '{@link #getSuperType() <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperType()
   * @generated
   * @ordered
   */
  protected Party superType;

  /**
   * The default value of the '{@link #getInsolvencyEvent() <em>Insolvency Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInsolvencyEvent()
   * @generated
   * @ordered
   */
  protected static final String INSOLVENCY_EVENT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getInsolvencyEvent() <em>Insolvency Event</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInsolvencyEvent()
   * @generated
   * @ordered
   */
  protected String insolvencyEvent = INSOLVENCY_EVENT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OnInsolvencyEventImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.ON_INSOLVENCY_EVENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Party getSuperType()
  {
    if (superType != null && superType.eIsProxy())
    {
      InternalEObject oldSuperType = (InternalEObject)superType;
      superType = (Party)eResolveProxy(oldSuperType);
      if (superType != oldSuperType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PactDSLPackage.ON_INSOLVENCY_EVENT__SUPER_TYPE, oldSuperType, superType));
      }
    }
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Party basicGetSuperType()
  {
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuperType(Party newSuperType)
  {
    Party oldSuperType = superType;
    superType = newSuperType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.ON_INSOLVENCY_EVENT__SUPER_TYPE, oldSuperType, superType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getInsolvencyEvent()
  {
    return insolvencyEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInsolvencyEvent(String newInsolvencyEvent)
  {
    String oldInsolvencyEvent = insolvencyEvent;
    insolvencyEvent = newInsolvencyEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.ON_INSOLVENCY_EVENT__INSOLVENCY_EVENT, oldInsolvencyEvent, insolvencyEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.ON_INSOLVENCY_EVENT__SUPER_TYPE:
        if (resolve) return getSuperType();
        return basicGetSuperType();
      case PactDSLPackage.ON_INSOLVENCY_EVENT__INSOLVENCY_EVENT:
        return getInsolvencyEvent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.ON_INSOLVENCY_EVENT__SUPER_TYPE:
        setSuperType((Party)newValue);
        return;
      case PactDSLPackage.ON_INSOLVENCY_EVENT__INSOLVENCY_EVENT:
        setInsolvencyEvent((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.ON_INSOLVENCY_EVENT__SUPER_TYPE:
        setSuperType((Party)null);
        return;
      case PactDSLPackage.ON_INSOLVENCY_EVENT__INSOLVENCY_EVENT:
        setInsolvencyEvent(INSOLVENCY_EVENT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.ON_INSOLVENCY_EVENT__SUPER_TYPE:
        return superType != null;
      case PactDSLPackage.ON_INSOLVENCY_EVENT__INSOLVENCY_EVENT:
        return INSOLVENCY_EVENT_EDEFAULT == null ? insolvencyEvent != null : !INSOLVENCY_EVENT_EDEFAULT.equals(insolvencyEvent);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (InsolvencyEvent: ");
    result.append(insolvencyEvent);
    result.append(')');
    return result.toString();
  }

} //OnInsolvencyEventImpl
