/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.ActionType;
import imperialmsc.lmw21.pactdsl.pactDSL.Address;
import imperialmsc.lmw21.pactdsl.pactDSL.ApplicableLaw;
import imperialmsc.lmw21.pactdsl.pactDSL.BoilerplateType;
import imperialmsc.lmw21.pactdsl.pactDSL.ByEmail;
import imperialmsc.lmw21.pactdsl.pactDSL.CompanyNumber;
import imperialmsc.lmw21.pactdsl.pactDSL.ConstraintParty;
import imperialmsc.lmw21.pactdsl.pactDSL.ConstraintThirdParty;
import imperialmsc.lmw21.pactdsl.pactDSL.CustomFeature;
import imperialmsc.lmw21.pactdsl.pactDSL.CustomFormality;
import imperialmsc.lmw21.pactdsl.pactDSL.CustomTermination;
import imperialmsc.lmw21.pactdsl.pactDSL.DefinedTerm;
import imperialmsc.lmw21.pactdsl.pactDSL.DeliveryObligation;
import imperialmsc.lmw21.pactdsl.pactDSL.EffectiveDate;
import imperialmsc.lmw21.pactdsl.pactDSL.EntityType;
import imperialmsc.lmw21.pactdsl.pactDSL.Feature;
import imperialmsc.lmw21.pactdsl.pactDSL.FeatureType;
import imperialmsc.lmw21.pactdsl.pactDSL.ForBreach;
import imperialmsc.lmw21.pactdsl.pactDSL.ForConvenience;
import imperialmsc.lmw21.pactdsl.pactDSL.FormalityType;
import imperialmsc.lmw21.pactdsl.pactDSL.GivenConsent;
import imperialmsc.lmw21.pactdsl.pactDSL.GivenWrittenConsent;
import imperialmsc.lmw21.pactdsl.pactDSL.GivingNotice;
import imperialmsc.lmw21.pactdsl.pactDSL.InWriting;
import imperialmsc.lmw21.pactdsl.pactDSL.Jurisdiction;
import imperialmsc.lmw21.pactdsl.pactDSL.LicenceObligation;
import imperialmsc.lmw21.pactdsl.pactDSL.Model;
import imperialmsc.lmw21.pactdsl.pactDSL.Notices;
import imperialmsc.lmw21.pactdsl.pactDSL.OnInsolvencyEvent;
import imperialmsc.lmw21.pactdsl.pactDSL.OnReasonableNotice;
import imperialmsc.lmw21.pactdsl.pactDSL.Ownership;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLFactory;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;
import imperialmsc.lmw21.pactdsl.pactDSL.Party;
import imperialmsc.lmw21.pactdsl.pactDSL.PaymentObligation;
import imperialmsc.lmw21.pactdsl.pactDSL.PrimaryObligationType;
import imperialmsc.lmw21.pactdsl.pactDSL.RightToUse;
import imperialmsc.lmw21.pactdsl.pactDSL.StateType;
import imperialmsc.lmw21.pactdsl.pactDSL.SubjectMatter;
import imperialmsc.lmw21.pactdsl.pactDSL.TerminationType;
import imperialmsc.lmw21.pactdsl.pactDSL.ThirdParty;
import imperialmsc.lmw21.pactdsl.pactDSL.TransferObligation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class PactDSLPackageImpl extends EPackageImpl implements PactDSLPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass entityTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass effectiveDateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass partyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass thirdPartyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass subjectMatterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass featureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass featureTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass definedTermEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass addressEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass companyNumberEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass customFeatureEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass formalityTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inWritingEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass byEmailEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass givingNoticeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass customFormalityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass actionTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass givenConsentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass givenWrittenConsentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stateTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ownershipEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass rightToUseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass primaryObligationTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass paymentObligationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass deliveryObligationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass transferObligationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass licenceObligationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintPartyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass constraintThirdPartyEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass terminationTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass forConvenienceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass onReasonableNoticeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass forBreachEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass onInsolvencyEventEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass customTerminationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass boilerplateTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass applicableLawEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass jurisdictionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass noticesEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private PactDSLPackageImpl()
  {
    super(eNS_URI, PactDSLFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link PactDSLPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static PactDSLPackage init()
  {
    if (isInited) return (PactDSLPackage)EPackage.Registry.INSTANCE.getEPackage(PactDSLPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredPactDSLPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    PactDSLPackageImpl thePactDSLPackage = registeredPactDSLPackage instanceof PactDSLPackageImpl ? (PactDSLPackageImpl)registeredPactDSLPackage : new PactDSLPackageImpl();

    isInited = true;

    // Create package meta-data objects
    thePactDSLPackage.createPackageContents();

    // Initialize created meta-data
    thePactDSLPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    thePactDSLPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(PactDSLPackage.eNS_URI, thePactDSLPackage);
    return thePactDSLPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getModel_Title()
  {
    return (EAttribute)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_EntityTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_FormalityTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_ActionTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_StateTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_PrimaryObligationTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_TerminationTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_BoilerplateTypes()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEntityType()
  {
    return entityTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getEffectiveDate()
  {
    return effectiveDateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEffectiveDate_Day()
  {
    return (EAttribute)effectiveDateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEffectiveDate_Month()
  {
    return (EAttribute)effectiveDateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getEffectiveDate_Year()
  {
    return (EAttribute)effectiveDateEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getParty()
  {
    return partyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getParty_Name()
  {
    return (EAttribute)partyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getParty_Fullname()
  {
    return (EAttribute)partyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getParty_Feature()
  {
    return (EReference)partyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getThirdParty()
  {
    return thirdPartyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getThirdParty_Name()
  {
    return (EAttribute)thirdPartyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getThirdParty_Fullname()
  {
    return (EAttribute)thirdPartyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getThirdParty_Feature()
  {
    return (EReference)thirdPartyEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSubjectMatter()
  {
    return subjectMatterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSubjectMatter_Name()
  {
    return (EAttribute)subjectMatterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSubjectMatter_SubjectMatter()
  {
    return (EAttribute)subjectMatterEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getSubjectMatter_Feature()
  {
    return (EReference)subjectMatterEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFeature()
  {
    return featureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getFeature_Featuretype()
  {
    return (EReference)featureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFeatureType()
  {
    return featureTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDefinedTerm()
  {
    return definedTermEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDefinedTerm_Definition()
  {
    return (EAttribute)definedTermEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddress()
  {
    return addressEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddress_Definition()
  {
    return (EAttribute)addressEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCompanyNumber()
  {
    return companyNumberEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCompanyNumber_Definition()
  {
    return (EAttribute)companyNumberEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCustomFeature()
  {
    return customFeatureEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCustomFeature_Feature()
  {
    return (EAttribute)customFeatureEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFormalityType()
  {
    return formalityTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInWriting()
  {
    return inWritingEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInWriting_CustomWritingFormality()
  {
    return (EAttribute)inWritingEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getByEmail()
  {
    return byEmailEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getByEmail_EmailAddress()
  {
    return (EAttribute)byEmailEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGivingNotice()
  {
    return givingNoticeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGivingNotice_SuperType()
  {
    return (EReference)givingNoticeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGivingNotice_NumDays()
  {
    return (EAttribute)givingNoticeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCustomFormality()
  {
    return customFormalityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCustomFormality_CustomFormality()
  {
    return (EAttribute)customFormalityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getActionType()
  {
    return actionTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getActionType_SuperType()
  {
    return (EReference)actionTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGivenConsent()
  {
    return givenConsentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGivenWrittenConsent()
  {
    return givenWrittenConsentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStateType()
  {
    return stateTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getStateType_SuperType()
  {
    return (EReference)stateTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOwnership()
  {
    return ownershipEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOwnership_CustomOwnership()
  {
    return (EAttribute)ownershipEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRightToUse()
  {
    return rightToUseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRightToUse_CustomUsage()
  {
    return (EAttribute)rightToUseEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPrimaryObligationType()
  {
    return primaryObligationTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrimaryObligationType_CustomObligation()
  {
    return (EAttribute)primaryObligationTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPrimaryObligationType_SuperType()
  {
    return (EReference)primaryObligationTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPaymentObligation()
  {
    return paymentObligationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPaymentObligation_Sum()
  {
    return (EAttribute)paymentObligationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPaymentObligation_Day()
  {
    return (EAttribute)paymentObligationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPaymentObligation_Month()
  {
    return (EAttribute)paymentObligationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPaymentObligation_Year()
  {
    return (EAttribute)paymentObligationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDeliveryObligation()
  {
    return deliveryObligationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeliveryObligation_Day()
  {
    return (EAttribute)deliveryObligationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeliveryObligation_Month()
  {
    return (EAttribute)deliveryObligationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDeliveryObligation_Year()
  {
    return (EAttribute)deliveryObligationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTransferObligation()
  {
    return transferObligationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTransferObligation_Day()
  {
    return (EAttribute)transferObligationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTransferObligation_Month()
  {
    return (EAttribute)transferObligationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTransferObligation_Year()
  {
    return (EAttribute)transferObligationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLicenceObligation()
  {
    return licenceObligationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLicenceObligation_Day()
  {
    return (EAttribute)licenceObligationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLicenceObligation_Month()
  {
    return (EAttribute)licenceObligationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLicenceObligation_Year()
  {
    return (EAttribute)licenceObligationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstraintParty()
  {
    return constraintPartyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstraintParty_ForbiddenAction()
  {
    return (EAttribute)constraintPartyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConstraintThirdParty()
  {
    return constraintThirdPartyEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstraintThirdParty_ForbiddenAction()
  {
    return (EAttribute)constraintThirdPartyEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConstraintThirdParty_AdditionalInfo()
  {
    return (EAttribute)constraintThirdPartyEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTerminationType()
  {
    return terminationTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getForConvenience()
  {
    return forConvenienceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getForConvenience_SuperType()
  {
    return (EReference)forConvenienceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getForConvenience_CustomTermination()
  {
    return (EAttribute)forConvenienceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOnReasonableNotice()
  {
    return onReasonableNoticeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOnReasonableNotice_SuperType()
  {
    return (EReference)onReasonableNoticeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getForBreach()
  {
    return forBreachEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getForBreach_SuperType()
  {
    return (EReference)forBreachEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getForBreach_ObligationBreached()
  {
    return (EAttribute)forBreachEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getForBreach_RemedialScheme()
  {
    return (EAttribute)forBreachEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOnInsolvencyEvent()
  {
    return onInsolvencyEventEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOnInsolvencyEvent_SuperType()
  {
    return (EReference)onInsolvencyEventEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getOnInsolvencyEvent_InsolvencyEvent()
  {
    return (EAttribute)onInsolvencyEventEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getCustomTermination()
  {
    return customTerminationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getCustomTermination_SuperType()
  {
    return (EReference)customTerminationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getCustomTermination_CustomTerminationClause()
  {
    return (EAttribute)customTerminationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBoilerplateType()
  {
    return boilerplateTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getApplicableLaw()
  {
    return applicableLawEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getApplicableLaw_CustomApplicableLaw()
  {
    return (EAttribute)applicableLawEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getApplicableLaw_Definition()
  {
    return (EReference)applicableLawEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getJurisdiction()
  {
    return jurisdictionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getJurisdiction_CustomJurisdiction()
  {
    return (EAttribute)jurisdictionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getJurisdiction_Definition()
  {
    return (EReference)jurisdictionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNotices()
  {
    return noticesEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNotices_CustomNotice()
  {
    return (EAttribute)noticesEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PactDSLFactory getPactDSLFactory()
  {
    return (PactDSLFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEAttribute(modelEClass, MODEL__TITLE);
    createEReference(modelEClass, MODEL__ENTITY_TYPES);
    createEReference(modelEClass, MODEL__FORMALITY_TYPES);
    createEReference(modelEClass, MODEL__ACTION_TYPES);
    createEReference(modelEClass, MODEL__STATE_TYPES);
    createEReference(modelEClass, MODEL__PRIMARY_OBLIGATION_TYPES);
    createEReference(modelEClass, MODEL__TERMINATION_TYPES);
    createEReference(modelEClass, MODEL__BOILERPLATE_TYPES);

    entityTypeEClass = createEClass(ENTITY_TYPE);

    effectiveDateEClass = createEClass(EFFECTIVE_DATE);
    createEAttribute(effectiveDateEClass, EFFECTIVE_DATE__DAY);
    createEAttribute(effectiveDateEClass, EFFECTIVE_DATE__MONTH);
    createEAttribute(effectiveDateEClass, EFFECTIVE_DATE__YEAR);

    partyEClass = createEClass(PARTY);
    createEAttribute(partyEClass, PARTY__NAME);
    createEAttribute(partyEClass, PARTY__FULLNAME);
    createEReference(partyEClass, PARTY__FEATURE);

    thirdPartyEClass = createEClass(THIRD_PARTY);
    createEAttribute(thirdPartyEClass, THIRD_PARTY__NAME);
    createEAttribute(thirdPartyEClass, THIRD_PARTY__FULLNAME);
    createEReference(thirdPartyEClass, THIRD_PARTY__FEATURE);

    subjectMatterEClass = createEClass(SUBJECT_MATTER);
    createEAttribute(subjectMatterEClass, SUBJECT_MATTER__NAME);
    createEAttribute(subjectMatterEClass, SUBJECT_MATTER__SUBJECT_MATTER);
    createEReference(subjectMatterEClass, SUBJECT_MATTER__FEATURE);

    featureEClass = createEClass(FEATURE);
    createEReference(featureEClass, FEATURE__FEATURETYPE);

    featureTypeEClass = createEClass(FEATURE_TYPE);

    definedTermEClass = createEClass(DEFINED_TERM);
    createEAttribute(definedTermEClass, DEFINED_TERM__DEFINITION);

    addressEClass = createEClass(ADDRESS);
    createEAttribute(addressEClass, ADDRESS__DEFINITION);

    companyNumberEClass = createEClass(COMPANY_NUMBER);
    createEAttribute(companyNumberEClass, COMPANY_NUMBER__DEFINITION);

    customFeatureEClass = createEClass(CUSTOM_FEATURE);
    createEAttribute(customFeatureEClass, CUSTOM_FEATURE__FEATURE);

    formalityTypeEClass = createEClass(FORMALITY_TYPE);

    inWritingEClass = createEClass(IN_WRITING);
    createEAttribute(inWritingEClass, IN_WRITING__CUSTOM_WRITING_FORMALITY);

    byEmailEClass = createEClass(BY_EMAIL);
    createEAttribute(byEmailEClass, BY_EMAIL__EMAIL_ADDRESS);

    givingNoticeEClass = createEClass(GIVING_NOTICE);
    createEReference(givingNoticeEClass, GIVING_NOTICE__SUPER_TYPE);
    createEAttribute(givingNoticeEClass, GIVING_NOTICE__NUM_DAYS);

    customFormalityEClass = createEClass(CUSTOM_FORMALITY);
    createEAttribute(customFormalityEClass, CUSTOM_FORMALITY__CUSTOM_FORMALITY);

    actionTypeEClass = createEClass(ACTION_TYPE);
    createEReference(actionTypeEClass, ACTION_TYPE__SUPER_TYPE);

    givenConsentEClass = createEClass(GIVEN_CONSENT);

    givenWrittenConsentEClass = createEClass(GIVEN_WRITTEN_CONSENT);

    stateTypeEClass = createEClass(STATE_TYPE);
    createEReference(stateTypeEClass, STATE_TYPE__SUPER_TYPE);

    ownershipEClass = createEClass(OWNERSHIP);
    createEAttribute(ownershipEClass, OWNERSHIP__CUSTOM_OWNERSHIP);

    rightToUseEClass = createEClass(RIGHT_TO_USE);
    createEAttribute(rightToUseEClass, RIGHT_TO_USE__CUSTOM_USAGE);

    primaryObligationTypeEClass = createEClass(PRIMARY_OBLIGATION_TYPE);
    createEAttribute(primaryObligationTypeEClass, PRIMARY_OBLIGATION_TYPE__CUSTOM_OBLIGATION);
    createEReference(primaryObligationTypeEClass, PRIMARY_OBLIGATION_TYPE__SUPER_TYPE);

    paymentObligationEClass = createEClass(PAYMENT_OBLIGATION);
    createEAttribute(paymentObligationEClass, PAYMENT_OBLIGATION__SUM);
    createEAttribute(paymentObligationEClass, PAYMENT_OBLIGATION__DAY);
    createEAttribute(paymentObligationEClass, PAYMENT_OBLIGATION__MONTH);
    createEAttribute(paymentObligationEClass, PAYMENT_OBLIGATION__YEAR);

    deliveryObligationEClass = createEClass(DELIVERY_OBLIGATION);
    createEAttribute(deliveryObligationEClass, DELIVERY_OBLIGATION__DAY);
    createEAttribute(deliveryObligationEClass, DELIVERY_OBLIGATION__MONTH);
    createEAttribute(deliveryObligationEClass, DELIVERY_OBLIGATION__YEAR);

    transferObligationEClass = createEClass(TRANSFER_OBLIGATION);
    createEAttribute(transferObligationEClass, TRANSFER_OBLIGATION__DAY);
    createEAttribute(transferObligationEClass, TRANSFER_OBLIGATION__MONTH);
    createEAttribute(transferObligationEClass, TRANSFER_OBLIGATION__YEAR);

    licenceObligationEClass = createEClass(LICENCE_OBLIGATION);
    createEAttribute(licenceObligationEClass, LICENCE_OBLIGATION__DAY);
    createEAttribute(licenceObligationEClass, LICENCE_OBLIGATION__MONTH);
    createEAttribute(licenceObligationEClass, LICENCE_OBLIGATION__YEAR);

    constraintPartyEClass = createEClass(CONSTRAINT_PARTY);
    createEAttribute(constraintPartyEClass, CONSTRAINT_PARTY__FORBIDDEN_ACTION);

    constraintThirdPartyEClass = createEClass(CONSTRAINT_THIRD_PARTY);
    createEAttribute(constraintThirdPartyEClass, CONSTRAINT_THIRD_PARTY__FORBIDDEN_ACTION);
    createEAttribute(constraintThirdPartyEClass, CONSTRAINT_THIRD_PARTY__ADDITIONAL_INFO);

    terminationTypeEClass = createEClass(TERMINATION_TYPE);

    forConvenienceEClass = createEClass(FOR_CONVENIENCE);
    createEReference(forConvenienceEClass, FOR_CONVENIENCE__SUPER_TYPE);
    createEAttribute(forConvenienceEClass, FOR_CONVENIENCE__CUSTOM_TERMINATION);

    onReasonableNoticeEClass = createEClass(ON_REASONABLE_NOTICE);
    createEReference(onReasonableNoticeEClass, ON_REASONABLE_NOTICE__SUPER_TYPE);

    forBreachEClass = createEClass(FOR_BREACH);
    createEReference(forBreachEClass, FOR_BREACH__SUPER_TYPE);
    createEAttribute(forBreachEClass, FOR_BREACH__OBLIGATION_BREACHED);
    createEAttribute(forBreachEClass, FOR_BREACH__REMEDIAL_SCHEME);

    onInsolvencyEventEClass = createEClass(ON_INSOLVENCY_EVENT);
    createEReference(onInsolvencyEventEClass, ON_INSOLVENCY_EVENT__SUPER_TYPE);
    createEAttribute(onInsolvencyEventEClass, ON_INSOLVENCY_EVENT__INSOLVENCY_EVENT);

    customTerminationEClass = createEClass(CUSTOM_TERMINATION);
    createEReference(customTerminationEClass, CUSTOM_TERMINATION__SUPER_TYPE);
    createEAttribute(customTerminationEClass, CUSTOM_TERMINATION__CUSTOM_TERMINATION_CLAUSE);

    boilerplateTypeEClass = createEClass(BOILERPLATE_TYPE);

    applicableLawEClass = createEClass(APPLICABLE_LAW);
    createEAttribute(applicableLawEClass, APPLICABLE_LAW__CUSTOM_APPLICABLE_LAW);
    createEReference(applicableLawEClass, APPLICABLE_LAW__DEFINITION);

    jurisdictionEClass = createEClass(JURISDICTION);
    createEAttribute(jurisdictionEClass, JURISDICTION__CUSTOM_JURISDICTION);
    createEReference(jurisdictionEClass, JURISDICTION__DEFINITION);

    noticesEClass = createEClass(NOTICES);
    createEAttribute(noticesEClass, NOTICES__CUSTOM_NOTICE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    effectiveDateEClass.getESuperTypes().add(this.getEntityType());
    partyEClass.getESuperTypes().add(this.getEntityType());
    thirdPartyEClass.getESuperTypes().add(this.getEntityType());
    subjectMatterEClass.getESuperTypes().add(this.getEntityType());
    definedTermEClass.getESuperTypes().add(this.getFeatureType());
    addressEClass.getESuperTypes().add(this.getFeatureType());
    companyNumberEClass.getESuperTypes().add(this.getFeatureType());
    customFeatureEClass.getESuperTypes().add(this.getFeatureType());
    inWritingEClass.getESuperTypes().add(this.getFormalityType());
    byEmailEClass.getESuperTypes().add(this.getFormalityType());
    givingNoticeEClass.getESuperTypes().add(this.getFormalityType());
    customFormalityEClass.getESuperTypes().add(this.getFormalityType());
    givenConsentEClass.getESuperTypes().add(this.getActionType());
    givenWrittenConsentEClass.getESuperTypes().add(this.getActionType());
    ownershipEClass.getESuperTypes().add(this.getStateType());
    rightToUseEClass.getESuperTypes().add(this.getStateType());
    paymentObligationEClass.getESuperTypes().add(this.getPrimaryObligationType());
    deliveryObligationEClass.getESuperTypes().add(this.getPrimaryObligationType());
    transferObligationEClass.getESuperTypes().add(this.getPrimaryObligationType());
    licenceObligationEClass.getESuperTypes().add(this.getPrimaryObligationType());
    constraintPartyEClass.getESuperTypes().add(this.getPrimaryObligationType());
    constraintThirdPartyEClass.getESuperTypes().add(this.getPrimaryObligationType());
    forConvenienceEClass.getESuperTypes().add(this.getTerminationType());
    onReasonableNoticeEClass.getESuperTypes().add(this.getTerminationType());
    forBreachEClass.getESuperTypes().add(this.getTerminationType());
    onInsolvencyEventEClass.getESuperTypes().add(this.getTerminationType());
    customTerminationEClass.getESuperTypes().add(this.getTerminationType());
    applicableLawEClass.getESuperTypes().add(this.getBoilerplateType());
    jurisdictionEClass.getESuperTypes().add(this.getBoilerplateType());
    noticesEClass.getESuperTypes().add(this.getBoilerplateType());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getModel_Title(), ecorePackage.getEString(), "title", null, 0, 1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_EntityTypes(), this.getEntityType(), null, "entityTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_FormalityTypes(), this.getFormalityType(), null, "formalityTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_ActionTypes(), this.getActionType(), null, "actionTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_StateTypes(), this.getStateType(), null, "stateTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_PrimaryObligationTypes(), this.getPrimaryObligationType(), null, "primaryObligationTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_TerminationTypes(), this.getTerminationType(), null, "terminationTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getModel_BoilerplateTypes(), this.getBoilerplateType(), null, "boilerplateTypes", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(entityTypeEClass, EntityType.class, "EntityType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(effectiveDateEClass, EffectiveDate.class, "EffectiveDate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getEffectiveDate_Day(), ecorePackage.getEInt(), "day", null, 0, 1, EffectiveDate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEffectiveDate_Month(), ecorePackage.getEInt(), "month", null, 0, 1, EffectiveDate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getEffectiveDate_Year(), ecorePackage.getEInt(), "year", null, 0, 1, EffectiveDate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(partyEClass, Party.class, "Party", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getParty_Name(), ecorePackage.getEString(), "name", null, 0, 1, Party.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getParty_Fullname(), ecorePackage.getEString(), "fullname", null, 0, 1, Party.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getParty_Feature(), this.getFeature(), null, "feature", null, 0, -1, Party.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(thirdPartyEClass, ThirdParty.class, "ThirdParty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getThirdParty_Name(), ecorePackage.getEString(), "name", null, 0, 1, ThirdParty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getThirdParty_Fullname(), ecorePackage.getEString(), "fullname", null, 0, 1, ThirdParty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getThirdParty_Feature(), this.getFeature(), null, "feature", null, 0, -1, ThirdParty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(subjectMatterEClass, SubjectMatter.class, "SubjectMatter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSubjectMatter_Name(), ecorePackage.getEString(), "name", null, 0, 1, SubjectMatter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSubjectMatter_SubjectMatter(), ecorePackage.getEString(), "subjectMatter", null, 0, 1, SubjectMatter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getSubjectMatter_Feature(), this.getFeature(), null, "feature", null, 0, -1, SubjectMatter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(featureEClass, Feature.class, "Feature", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getFeature_Featuretype(), this.getFeatureType(), null, "featuretype", null, 0, 1, Feature.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(featureTypeEClass, FeatureType.class, "FeatureType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(definedTermEClass, DefinedTerm.class, "DefinedTerm", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDefinedTerm_Definition(), ecorePackage.getEString(), "definition", null, 0, 1, DefinedTerm.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(addressEClass, Address.class, "Address", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAddress_Definition(), ecorePackage.getEString(), "definition", null, 0, 1, Address.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(companyNumberEClass, CompanyNumber.class, "CompanyNumber", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCompanyNumber_Definition(), ecorePackage.getEString(), "definition", null, 0, 1, CompanyNumber.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(customFeatureEClass, CustomFeature.class, "CustomFeature", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCustomFeature_Feature(), ecorePackage.getEString(), "feature", null, 0, 1, CustomFeature.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(formalityTypeEClass, FormalityType.class, "FormalityType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(inWritingEClass, InWriting.class, "InWriting", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInWriting_CustomWritingFormality(), ecorePackage.getEString(), "customWritingFormality", null, 0, 1, InWriting.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(byEmailEClass, ByEmail.class, "ByEmail", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getByEmail_EmailAddress(), ecorePackage.getEString(), "emailAddress", null, 0, 1, ByEmail.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(givingNoticeEClass, GivingNotice.class, "GivingNotice", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getGivingNotice_SuperType(), this.getParty(), null, "superType", null, 0, 1, GivingNotice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGivingNotice_NumDays(), ecorePackage.getEInt(), "numDays", null, 0, 1, GivingNotice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(customFormalityEClass, CustomFormality.class, "CustomFormality", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getCustomFormality_CustomFormality(), ecorePackage.getEString(), "customFormality", null, 0, 1, CustomFormality.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(actionTypeEClass, ActionType.class, "ActionType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getActionType_SuperType(), this.getParty(), null, "superType", null, 0, 1, ActionType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(givenConsentEClass, GivenConsent.class, "GivenConsent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(givenWrittenConsentEClass, GivenWrittenConsent.class, "GivenWrittenConsent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stateTypeEClass, StateType.class, "StateType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStateType_SuperType(), this.getEntityType(), null, "superType", null, 0, 1, StateType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ownershipEClass, Ownership.class, "Ownership", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getOwnership_CustomOwnership(), ecorePackage.getEString(), "customOwnership", null, 0, 1, Ownership.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(rightToUseEClass, RightToUse.class, "RightToUse", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRightToUse_CustomUsage(), ecorePackage.getEString(), "customUsage", null, 0, 1, RightToUse.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(primaryObligationTypeEClass, PrimaryObligationType.class, "PrimaryObligationType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPrimaryObligationType_CustomObligation(), ecorePackage.getEString(), "CustomObligation", null, 0, 1, PrimaryObligationType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPrimaryObligationType_SuperType(), this.getEntityType(), null, "superType", null, 0, 1, PrimaryObligationType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(paymentObligationEClass, PaymentObligation.class, "PaymentObligation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPaymentObligation_Sum(), ecorePackage.getEInt(), "sum", null, 0, 1, PaymentObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPaymentObligation_Day(), ecorePackage.getEInt(), "day", null, 0, 1, PaymentObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPaymentObligation_Month(), ecorePackage.getEInt(), "month", null, 0, 1, PaymentObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getPaymentObligation_Year(), ecorePackage.getEInt(), "year", null, 0, 1, PaymentObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(deliveryObligationEClass, DeliveryObligation.class, "DeliveryObligation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDeliveryObligation_Day(), ecorePackage.getEInt(), "day", null, 0, 1, DeliveryObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeliveryObligation_Month(), ecorePackage.getEInt(), "month", null, 0, 1, DeliveryObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDeliveryObligation_Year(), ecorePackage.getEInt(), "year", null, 0, 1, DeliveryObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(transferObligationEClass, TransferObligation.class, "TransferObligation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTransferObligation_Day(), ecorePackage.getEInt(), "day", null, 0, 1, TransferObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTransferObligation_Month(), ecorePackage.getEInt(), "month", null, 0, 1, TransferObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTransferObligation_Year(), ecorePackage.getEInt(), "year", null, 0, 1, TransferObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(licenceObligationEClass, LicenceObligation.class, "LicenceObligation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLicenceObligation_Day(), ecorePackage.getEInt(), "day", null, 0, 1, LicenceObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLicenceObligation_Month(), ecorePackage.getEInt(), "month", null, 0, 1, LicenceObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLicenceObligation_Year(), ecorePackage.getEInt(), "year", null, 0, 1, LicenceObligation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintPartyEClass, ConstraintParty.class, "ConstraintParty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraintParty_ForbiddenAction(), ecorePackage.getEString(), "forbiddenAction", null, 0, 1, ConstraintParty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(constraintThirdPartyEClass, ConstraintThirdParty.class, "ConstraintThirdParty", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConstraintThirdParty_ForbiddenAction(), ecorePackage.getEString(), "forbiddenAction", null, 0, 1, ConstraintThirdParty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConstraintThirdParty_AdditionalInfo(), ecorePackage.getEString(), "additionalInfo", null, 0, 1, ConstraintThirdParty.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(terminationTypeEClass, TerminationType.class, "TerminationType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(forConvenienceEClass, ForConvenience.class, "ForConvenience", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getForConvenience_SuperType(), this.getParty(), null, "superType", null, 0, 1, ForConvenience.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getForConvenience_CustomTermination(), ecorePackage.getEString(), "customTermination", null, 0, 1, ForConvenience.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(onReasonableNoticeEClass, OnReasonableNotice.class, "OnReasonableNotice", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOnReasonableNotice_SuperType(), ecorePackage.getEObject(), null, "superType", null, 0, 1, OnReasonableNotice.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(forBreachEClass, ForBreach.class, "ForBreach", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getForBreach_SuperType(), this.getParty(), null, "superType", null, 0, 1, ForBreach.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getForBreach_ObligationBreached(), ecorePackage.getEString(), "ObligationBreached", null, 0, 1, ForBreach.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getForBreach_RemedialScheme(), ecorePackage.getEString(), "RemedialScheme", null, 0, 1, ForBreach.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(onInsolvencyEventEClass, OnInsolvencyEvent.class, "OnInsolvencyEvent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOnInsolvencyEvent_SuperType(), this.getParty(), null, "superType", null, 0, 1, OnInsolvencyEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getOnInsolvencyEvent_InsolvencyEvent(), ecorePackage.getEString(), "InsolvencyEvent", null, 0, 1, OnInsolvencyEvent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(customTerminationEClass, CustomTermination.class, "CustomTermination", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getCustomTermination_SuperType(), ecorePackage.getEObject(), null, "superType", null, 0, 1, CustomTermination.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getCustomTermination_CustomTerminationClause(), ecorePackage.getEString(), "CustomTerminationClause", null, 0, 1, CustomTermination.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(boilerplateTypeEClass, BoilerplateType.class, "BoilerplateType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(applicableLawEClass, ApplicableLaw.class, "ApplicableLaw", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getApplicableLaw_CustomApplicableLaw(), ecorePackage.getEString(), "CustomApplicableLaw", null, 0, 1, ApplicableLaw.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getApplicableLaw_Definition(), this.getDefinedTerm(), null, "definition", null, 0, -1, ApplicableLaw.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(jurisdictionEClass, Jurisdiction.class, "Jurisdiction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getJurisdiction_CustomJurisdiction(), ecorePackage.getEString(), "CustomJurisdiction", null, 0, 1, Jurisdiction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getJurisdiction_Definition(), this.getDefinedTerm(), null, "definition", null, 0, -1, Jurisdiction.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(noticesEClass, Notices.class, "Notices", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNotices_CustomNotice(), ecorePackage.getEString(), "CustomNotice", null, 0, 1, Notices.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //PactDSLPackageImpl
