/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.EntityType;
import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;
import imperialmsc.lmw21.pactdsl.pactDSL.PrimaryObligationType;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primary Obligation Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.PrimaryObligationTypeImpl#getCustomObligation <em>Custom Obligation</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.PrimaryObligationTypeImpl#getSuperType <em>Super Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimaryObligationTypeImpl extends MinimalEObjectImpl.Container implements PrimaryObligationType
{
  /**
   * The default value of the '{@link #getCustomObligation() <em>Custom Obligation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomObligation()
   * @generated
   * @ordered
   */
  protected static final String CUSTOM_OBLIGATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCustomObligation() <em>Custom Obligation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomObligation()
   * @generated
   * @ordered
   */
  protected String customObligation = CUSTOM_OBLIGATION_EDEFAULT;

  /**
   * The cached value of the '{@link #getSuperType() <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperType()
   * @generated
   * @ordered
   */
  protected EntityType superType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimaryObligationTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.PRIMARY_OBLIGATION_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCustomObligation()
  {
    return customObligation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCustomObligation(String newCustomObligation)
  {
    String oldCustomObligation = customObligation;
    customObligation = newCustomObligation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.PRIMARY_OBLIGATION_TYPE__CUSTOM_OBLIGATION, oldCustomObligation, customObligation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EntityType getSuperType()
  {
    if (superType != null && superType.eIsProxy())
    {
      InternalEObject oldSuperType = (InternalEObject)superType;
      superType = (EntityType)eResolveProxy(oldSuperType);
      if (superType != oldSuperType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PactDSLPackage.PRIMARY_OBLIGATION_TYPE__SUPER_TYPE, oldSuperType, superType));
      }
    }
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EntityType basicGetSuperType()
  {
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuperType(EntityType newSuperType)
  {
    EntityType oldSuperType = superType;
    superType = newSuperType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.PRIMARY_OBLIGATION_TYPE__SUPER_TYPE, oldSuperType, superType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__CUSTOM_OBLIGATION:
        return getCustomObligation();
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__SUPER_TYPE:
        if (resolve) return getSuperType();
        return basicGetSuperType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__CUSTOM_OBLIGATION:
        setCustomObligation((String)newValue);
        return;
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__SUPER_TYPE:
        setSuperType((EntityType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__CUSTOM_OBLIGATION:
        setCustomObligation(CUSTOM_OBLIGATION_EDEFAULT);
        return;
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__SUPER_TYPE:
        setSuperType((EntityType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__CUSTOM_OBLIGATION:
        return CUSTOM_OBLIGATION_EDEFAULT == null ? customObligation != null : !CUSTOM_OBLIGATION_EDEFAULT.equals(customObligation);
      case PactDSLPackage.PRIMARY_OBLIGATION_TYPE__SUPER_TYPE:
        return superType != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (CustomObligation: ");
    result.append(customObligation);
    result.append(')');
    return result.toString();
  }

} //PrimaryObligationTypeImpl
