/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;
import imperialmsc.lmw21.pactdsl.pactDSL.Party;
import imperialmsc.lmw21.pactdsl.pactDSL.SecondaryObligationType;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Secondary Obligation Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.SecondaryObligationTypeImpl#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.SecondaryObligationTypeImpl#getSum <em>Sum</em>}</li>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.SecondaryObligationTypeImpl#getCustomPrimaryObligation <em>Custom Primary Obligation</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SecondaryObligationTypeImpl extends MinimalEObjectImpl.Container implements SecondaryObligationType
{
  /**
   * The cached value of the '{@link #getSuperType() <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSuperType()
   * @generated
   * @ordered
   */
  protected Party superType;

  /**
   * The default value of the '{@link #getSum() <em>Sum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSum()
   * @generated
   * @ordered
   */
  protected static final int SUM_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSum() <em>Sum</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSum()
   * @generated
   * @ordered
   */
  protected int sum = SUM_EDEFAULT;

  /**
   * The default value of the '{@link #getCustomPrimaryObligation() <em>Custom Primary Obligation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomPrimaryObligation()
   * @generated
   * @ordered
   */
  protected static final String CUSTOM_PRIMARY_OBLIGATION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCustomPrimaryObligation() <em>Custom Primary Obligation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomPrimaryObligation()
   * @generated
   * @ordered
   */
  protected String customPrimaryObligation = CUSTOM_PRIMARY_OBLIGATION_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SecondaryObligationTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.SECONDARY_OBLIGATION_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Party getSuperType()
  {
    if (superType != null && superType.eIsProxy())
    {
      InternalEObject oldSuperType = (InternalEObject)superType;
      superType = (Party)eResolveProxy(oldSuperType);
      if (superType != oldSuperType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUPER_TYPE, oldSuperType, superType));
      }
    }
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Party basicGetSuperType()
  {
    return superType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSuperType(Party newSuperType)
  {
    Party oldSuperType = superType;
    superType = newSuperType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUPER_TYPE, oldSuperType, superType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSum()
  {
    return sum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSum(int newSum)
  {
    int oldSum = sum;
    sum = newSum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUM, oldSum, sum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCustomPrimaryObligation()
  {
    return customPrimaryObligation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCustomPrimaryObligation(String newCustomPrimaryObligation)
  {
    String oldCustomPrimaryObligation = customPrimaryObligation;
    customPrimaryObligation = newCustomPrimaryObligation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.SECONDARY_OBLIGATION_TYPE__CUSTOM_PRIMARY_OBLIGATION, oldCustomPrimaryObligation, customPrimaryObligation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUPER_TYPE:
        if (resolve) return getSuperType();
        return basicGetSuperType();
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUM:
        return getSum();
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__CUSTOM_PRIMARY_OBLIGATION:
        return getCustomPrimaryObligation();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUPER_TYPE:
        setSuperType((Party)newValue);
        return;
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUM:
        setSum((Integer)newValue);
        return;
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__CUSTOM_PRIMARY_OBLIGATION:
        setCustomPrimaryObligation((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUPER_TYPE:
        setSuperType((Party)null);
        return;
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUM:
        setSum(SUM_EDEFAULT);
        return;
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__CUSTOM_PRIMARY_OBLIGATION:
        setCustomPrimaryObligation(CUSTOM_PRIMARY_OBLIGATION_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUPER_TYPE:
        return superType != null;
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__SUM:
        return sum != SUM_EDEFAULT;
      case PactDSLPackage.SECONDARY_OBLIGATION_TYPE__CUSTOM_PRIMARY_OBLIGATION:
        return CUSTOM_PRIMARY_OBLIGATION_EDEFAULT == null ? customPrimaryObligation != null : !CUSTOM_PRIMARY_OBLIGATION_EDEFAULT.equals(customPrimaryObligation);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sum: ");
    result.append(sum);
    result.append(", customPrimaryObligation: ");
    result.append(customPrimaryObligation);
    result.append(')');
    return result.toString();
  }

} //SecondaryObligationTypeImpl
