/**
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.pactDSL.impl;

import imperialmsc.lmw21.pactdsl.pactDSL.PactDSLPackage;
import imperialmsc.lmw21.pactdsl.pactDSL.SubjectMatter;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subject Matter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link imperialmsc.lmw21.pactdsl.pactDSL.impl.SubjectMatterImpl#getSubjectMatter <em>Subject Matter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubjectMatterImpl extends EntityTypeImpl implements SubjectMatter
{
  /**
   * The default value of the '{@link #getSubjectMatter() <em>Subject Matter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubjectMatter()
   * @generated
   * @ordered
   */
  protected static final String SUBJECT_MATTER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSubjectMatter() <em>Subject Matter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSubjectMatter()
   * @generated
   * @ordered
   */
  protected String subjectMatter = SUBJECT_MATTER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubjectMatterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PactDSLPackage.Literals.SUBJECT_MATTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSubjectMatter()
  {
    return subjectMatter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSubjectMatter(String newSubjectMatter)
  {
    String oldSubjectMatter = subjectMatter;
    subjectMatter = newSubjectMatter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PactDSLPackage.SUBJECT_MATTER__SUBJECT_MATTER, oldSubjectMatter, subjectMatter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PactDSLPackage.SUBJECT_MATTER__SUBJECT_MATTER:
        return getSubjectMatter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PactDSLPackage.SUBJECT_MATTER__SUBJECT_MATTER:
        setSubjectMatter((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.SUBJECT_MATTER__SUBJECT_MATTER:
        setSubjectMatter(SUBJECT_MATTER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PactDSLPackage.SUBJECT_MATTER__SUBJECT_MATTER:
        return SUBJECT_MATTER_EDEFAULT == null ? subjectMatter != null : !SUBJECT_MATTER_EDEFAULT.equals(subjectMatter);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (subjectMatter: ");
    result.append(subjectMatter);
    result.append(')');
    return result.toString();
  }

} //SubjectMatterImpl
