/*
 * generated by Xtext 2.25.0
 */
package imperialmsc.lmw21.pactdsl.parser.antlr;

import com.google.inject.Inject;
import imperialmsc.lmw21.pactdsl.parser.antlr.internal.InternalPactDSLParser;
import imperialmsc.lmw21.pactdsl.services.PactDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PactDSLParser extends AbstractAntlrParser {

	@Inject
	private PactDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPactDSLParser createParser(XtextTokenStream stream) {
		return new InternalPactDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public PactDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PactDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
